# Generated by Django 3.2 on 2021-08-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
