# Generated by Django 3.2 on 2021-09-08 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210831_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='Profile_Pics', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
