# Generated by Django 3.2 on 2021-09-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.CharField(default='Maths', max_length=50),
        ),
    ]
