# Generated by Django 3.2 on 2021-09-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_notes_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
