# Generated by Django 3.2 on 2021-09-06 09:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0004_alter_notes_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_title', models.CharField(max_length=60)),
                ('vid_subject', models.CharField(max_length=50)),
                ('vid_desc', models.TextField(blank=True, default='description')),
                ('vid_video', models.FileField(upload_to='Videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[''])])),
                ('vid_published_on', models.DateTimeField(auto_now_add=True)),
                ('vid_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
