# Generated by Django 3.2 on 2021-09-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210907_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vid_views',
            field=models.IntegerField(default=0),
        ),
    ]
