# Generated by Django 3.2 on 2021-09-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_video_vid_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default_notes.jpeg', upload_to='thumbnail_notes'),
        ),
    ]
