# Generated by Django 3.2 on 2021-09-08 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_notes_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vid_thumbnail',
            field=models.ImageField(blank=True, default='default_video.jpeg', upload_to='thumbnail_video', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='notes',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default_notes.jpeg', upload_to='thumbnail_notes', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
