# Generated by Django 3.2 on 2021-09-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_notes_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='desc',
            field=models.TextField(blank=True, default='Description'),
        ),
    ]
