# Generated by Django 3.2 on 2021-10-02 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_alter_notes_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default_notes.jpeg', null=True, upload_to='thumbnail_notes', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
