# Generated by Django 3.2 on 2021-10-04 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20211002_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid_video',
            field=models.FileField(upload_to='Videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'MOV', 'WMV', 'AVI', 'AVCHD', 'FLV', 'F4V', 'SWF', 'MKV'])]),
        ),
    ]
