# Generated by Django 3.2 on 2021-10-04 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_alter_video_vid_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid_thumbnail',
            field=models.ImageField(blank=True, default='default_video.jpeg', null=True, upload_to='thumbnail_video', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
