# Generated by Django 3.2 on 2021-10-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20211005_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid_desc',
            field=models.TextField(blank=True, default='description'),
        ),
    ]
