# Generated by Django 3.2 on 2021-10-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_alter_video_vid_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
