# Generated by Django 3.2 on 2021-10-13 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_alter_notes_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='thumbnail',
            field=models.ImageField(default='default_notes.jpeg', null=True, upload_to='thumbnail_notes', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
