# Generated by Django 3.2 on 2021-10-14 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0023_alter_notes_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid_subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
