# Generated by Django 3.2 on 2021-10-14 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_auto_20211014_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid_thumbnail',
            field=models.ImageField(blank=True, default='default_video.jpeg', upload_to='thumbnail_video', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
