# Generated by Django 3.2 on 2021-10-28 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0025_alter_video_vid_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=35)),
                ('q1', models.CharField(max_length=80)),
                ('q2', models.CharField(max_length=80)),
                ('q3', models.CharField(max_length=80)),
                ('q4', models.CharField(max_length=80)),
                ('q5', models.CharField(max_length=80)),
                ('q6', models.CharField(max_length=80)),
                ('q7', models.CharField(max_length=80)),
                ('q8', models.CharField(max_length=80)),
                ('q9', models.CharField(max_length=80)),
                ('q10', models.CharField(max_length=80)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
