# Generated by Django 3.2 on 2021-10-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
