# Generated by Django 3.2 on 2021-10-29 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_delete_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
