# Generated by Django 3.2 on 2021-10-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
