# Generated by Django 3.2 on 2021-10-31 10:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0029_alter_notes_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_title', models.CharField(max_length=60)),
                ('vid_subject', models.CharField(blank=True, max_length=50, null=True)),
                ('vid_desc', models.TextField(blank=True, null=True)),
                ('vid_thumbnail', models.ImageField(blank=True, default='default_video.jpeg', upload_to='thumbnail_video', validators=[django.core.validators.validate_image_file_extension])),
                ('vid_video', models.FileField(upload_to='Videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'MOV', 'WMV', 'AVI', 'AVCHD', 'FLV', 'F4V', 'SWF', 'MKV'])])),
                ('vid_published_on', models.DateTimeField(auto_now_add=True)),
                ('vid_views', models.IntegerField(default=0)),
                ('vid_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=90, unique=True)),
                ('course_desc', models.TextField()),
                ('course_thumbnail', models.ImageField(blank=True, default='default_course.', null=True, upload_to='Course_Thumbnail', validators=[django.core.validators.validate_image_file_extension])),
                ('course_published_on', models.DateTimeField(auto_now_add=True)),
                ('course_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course_videos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.video')),
            ],
        ),
    ]
